### ISSUE TITLE
Process list shows processes within Category that shouldn't be visible by user.

### ISSUE THREAD

**Issue by arkadius** [TouK/nussknacker#121]
**Describe the bug**
For user, on the list of processes are visible all processes - even if he/she hasn't got configured Read permission for some category.

**To Reproduce**
1. Having Flink and Nussknacker ran e.g. in docker with configured two categories: one visible for user A and the second not visible.
2. Open browser, login as a user A and go to 'main page'

**Expected behavior**
User A should see processes in categories that he/she has Read permission,
, but:
User A see all processes.

**Comment by lciolecki** [comment]
Problem is with admin persmissions. Now we have bad checking user is admin, because when at one category he has Admin permission then he is admin at all system .. We shoud add additional property  named isAdmin and remove old Admin permission at category.

Classes / Objects to change: LoggedUser and PermissionSyntax.
