### ISSUE TITLE
design "tip panel" content calculation and presentation

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#363]
It will be some combination of: 
level: error, warning
and place of an error: process properties, global, node, node property, edge

**Comment by witekw** [comment]
Data
![image](https://user-images.githubusercontent.com/632221/69059242-7020a500-0a15-11ea-8003-30f9dd298370.png)

UI
![image](https://user-images.githubusercontent.com/632221/69059261-7747b300-0a15-11ea-88be-14b92c5844bb.png)

**Comment by fi-** [comment]
should look like this:
![errors-warnings](https://user-images.githubusercontent.com/8850099/69324205-5024f780-0c48-11ea-87bc-74c9667427ff.jpg)

here is icon:
[error.zip](https://github.com/TouK/nussknacker/files/3873846/error.zip)

here are colors for error:
#f25c6e - main color. It is not as red as #ff0000 because reds are generally hard to read, so I make it lighter for its readability.
#fbd2d6 - node fill color
