### ISSUE TITLE
Source should be able to control start variables

### ISSUE THREAD

**Issue by mproch** [TouK/nussknacker#548]
Currently we're fixed on single "input" variable. Source should have possibility to define what variables it provides

**Comment by gskrobisz** [comment]
--------------------------------------------------------
General concept
--------------------------------------------------------

Context initialization

Typical FlinkSource uses FlinkSourceFunction to fetch raw data, performs common transformations and maps stream of raw data to stream of Context with "variables"
(this happens "between" raw source data and realeasing prepared source stream, hence "intermediate" in FlinkIntermediateRawSource).
To initialize context FlinkContextInitializer is used. It provides both definition of variables (ValidationContext) and their values (Context).
Custom variable definition can be provided within sources based on GenericNodeTransformation (so far), initContext can be used in all sources.
Default implementation of FlinkContextInitializer sets singe "input" variable with raw event value (see BasicFlinkContextInitializer).

Kafka

Use new KafkaGenericNodeSourceFactory to access metadata as an extra variable.

`KafkaSource` uses this basic approach (to be used with legacy sources and ConsumerRecord-to-value deserializers).
KafkaSourceFactory, due to its limitations, provides single variable and single value.

For kafka (and kafka avro) sources use deserialization to ConsumerRecord[K, V] - this should be default scenario.
ConsumerRecordDeserializationSchemaFactory has a default implementation of "create" deserializer method.
While such deserialization is provided, KafkaGenericNodeSourceFactory is able to use KafkaContextInitializer to initialize context with two variables: "input" and "inputMeta".


KafkaAvro

All current kafka avro sources get access to metadata via extra variable.

`KafkaAvroSourceFactory` recognizes value and key schema with `BaseKafkaAvroSourceFactory`, uses key-value deserializer that must produce `ConsumerRecord[K, V]`,
which is further used to initialize context with `KafkaAvroContextInitializer` (if key schema is not provided it is assumed that key is a String, here key=null is allowed).

KafkaAvroDeserializationSchemaFactory uses both key and value schema (for generic records) and `ClassTag`s (for SpecificRecord)

KafkaAvroKeyValueDeserializationSchemaFactory
  Creates source that transforms raw kafka input to `ConsumerRecord[K, V]` that contains value, key and metadata (topic, partition, offset, headers etc).
  When combined with `KafkaGenericNodeSource` it allows to stream events initialized with value, key and metadata.
  Deserializers based on `KafkaAvroValueDeserializationSchemaFactory` should implement safe fallback to key-as-String deserialization.

ConfluentConsumerRecordKafkaAvroDeserializationFactory
`ConfluentJsonPayloadDeserializerFactory`
SpecificRecordKafkaAvroSourceFactory


--------------------------------------------------------
Deprecated:
--------------------------------------------------------
KafkaSourceFactory
KafkaAvroValueDeserializationSchemaFactory
ConfluentKafkaAvroDeserializationSchemaFactory
ConfluentJsonPayloadDeserializerFactory

--------------------------------------------------------
Side quests, fixes and refactoring:
--------------------------------------------------------
`FlinkSource`.`sourceStream` returns stream with initialized context `DataStream[Context]`
FlinkIntermediateRawSource is used to create source with typical stream transformations, eg BaseFlinkSource.
  It separates raw event data produced by SourceFunction and data released to the stream as Context variables.
  Also enhances FlinkSource with FlinkContextInitializer that is used to map stream of raw event [T] to stream of [Context] with proper variable initialization.
  Default option is BasicFlinkContextInitializer that initializes only "input" variable with value of raw event.
What was related to "test source" functionality and was obsolete in FlinkSource now is excluded to FlinkSourceTestSupport.
Rename `TestDataParserProvider` to `SourceTestSupport`
To enable "test source" functionality, a source needs to be extended with `SourceTestSupport`.
To enable test data generator for "test source" , a source needs to be extended with `SourceTestSupport` and `TestDataGenerator`.
FlinkCustomNodeContext has access to TypeInformationDetection, it allows to get TypeInformation for the node stream mapping from ValidationContext.
RecordFormatter parses raw test data to ConsumerRecord which fits into deserializer (instead of ProducerRecord that required another transformation).
KafkaAvroKeyValueDeserializationSchemaFactory uses ClassTags for SpecificRecord.
Definition of names of common variables are moved `VariableConstants` (from Interpreter)
`ConfluentAvroToJsonFormatter` and `ConfluentAvroMessageReader` allows to use empty (null) key when key formatting is enabled.
`ConfluentUtils.parsePayloadToByteBuffer` gives better exception info when payload is null.

--------------------------------------------------------
TODO
--------------------------------------------------------
`FlinkSource` should not depend on type T.
Probably better approach to FlinkSourceTestSupport and FlinkIntermediateRawSource.typeInformation should be provided.
Add key deserialization for sources based on SpecificRecord.
Add key schema versioning in KafkaAvroSourceFactory.
ConfluentSchemaRegistryProvider -> parameter formatKey seems to be always true (in default scenario we produce and serialize whole ConsumerRecord).
