### ISSUE TITLE
Presentation of process state on process details view

### ISSUE THREAD

**Issue by arkadius** [TouK/nussknacker#584]
As a user I would like to see exact state of deployment in two places: on 1) list of processes and 2) process details

**Comment by fi-** [comment]
![Asset 41-100](https://user-images.githubusercontent.com/8850099/72521239-5a83fc00-385b-11ea-8c90-0d9dd214f82c.jpg)

Only the upper part of this screen is relevant for this task*. The icon shows the process state. We will also display the name of the process there instead of it being displayed in the corner of graph edit area. Below the process name we have process state label/description that corresponds to the icon.

*this is due to redesign that is taking place in the background which will make the space avaliable used more efficiently
